require "pickol"  
pic.ellipse("document")  
pic.arrow()  
pic.box("PIC")  
pic.arrow()  
pic.box("TBL/EQN","(optional)",dashed)  
pic.arrow()  
pic.box("TROFF")  
pic.arrow()  
pic.ellipse("typesetter")
